- hosts: localhost
  collections:
    - awx.awx

  tasks:

    - name: Waits for AWX to be up and running before starting
      ansible.builtin.wait_for:
        host: localhost
        port: 8013
        timeout: 900

    - name: create awx-cli config file
      template:
        src: awx-cli.cfg.j2
        dest: awx-cli.cfg
      no_log: true

    - name: Add organization
      organization:
        name: test-suite
        description: "Test suite"
        controller_config_file: awx-cli.cfg

    - name: Add project
      project:
        description: Test suite project
        name: test-suite
        scm_allow_override: true
        scm_branch: "{{ project_default | default(omit) }}"
        scm_type: git
        scm_url: https://github.com/willthames/awx-project-update-test-suite.git
        scm_update_on_launch: true
        scm_clean: true
        organization: test-suite
        controller_config_file: awx-cli.cfg

    - name: Add inventory
      inventory:
        name: test-suite
        organization: test-suite
        controller_config_file: awx-cli.cfg

    - name: Add inventory source
      inventory_source:
        name: test-suite
        inventory: test-suite
        source_project: test-suite
        source_path: inventory
        source: scm
        update_on_launch: true
        overwrite_vars: true
        overwrite: true
        organization: test-suite
        controller_config_file: awx-cli.cfg

    - name: Create job template
      job_template:
        name: Test suite
        job_type: run
        inventory: test-suite
        project: test-suite
        ask_variables_on_launch: true
        ask_verbosity_on_launch: true
        ask_scm_branch_on_launch: true
        scm_branch: job-default
        playbook: playbook.yml
        diff_mode: true
        controller_config_file: awx-cli.cfg
