- hosts: test
  connection: local
  vars:
    branch: main

  tasks:
    - debug:
        var: version

    - debug:
        var: expected

    - debug:
        var: sequence

    - name: inventory version should match expected 
      assert:
        that:
          - version == expected

    - name: project branch should match expected
      assert:
        that:
          - branch  == expected
