- hosts: localhost
  collections:
    - awx.awx

  tasks:
    - name: run job with defaults
      job_launch:
        job_template: Test suite
        extra_vars:
          expected: job-default
        controller_config_file: "{{ playbook_dir }}/../awx-cli.cfg"
      register: job1

    - name: wait for job
      job_wait:
        job_id: "{{ job1.id }}"
        timeout: 300
        controller_config_file: "{{ playbook_dir }}/../awx-cli.cfg"

    - name: get result
      job_list:
        query:
          id: "{{ job1.id }}"
        controller_config_file: "{{ playbook_dir }}/../awx-cli.cfg"
      register: job1_result

    - name: check result
      assert:
        that:
          - job1_result.results | length == 1
          - 'job1_result.results[0].status == "successful"'
